#ifndef LV_CONF_H
#define LV_CONF_H
#define LV_COLOR_DEPTH 16
#define LV_USE_STDLIB_MALLOC LV_STDLIB_CLIB
#define LV_USE_OS LV_OS_NONE
#define LV_USE_LOG 0
#define LV_CACHE_DEF_SIZE 16384
#define LV_IMAGE_HEADER_CACHE_DEF_CNT 8
#define LV_USE_THORVG_INTERNAL 0

#endif
